title: "Anuj Pandey"
description: >
  Data Scientist and AI Engineer working at the intersection of
  machine learning, bioprocessing, and pharmaceutical manufacturing.

url: "https://anujpandey10.github.io"
baseurl: ""   # <-- THIS IS THE KEY LINE

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
